### ISSUE TITLE
Wrong warn level posted to sentry

### ISSUE THREAD

**Issue by ndt93** [hayesgm/ravenex#1]
For `warn` log level, sentry expects the value of `level` posted to be "warning".

Should convert from Elixir _Logger_'s level to sentry's corresponding level before posting to sentry.

**Comment by hayesgm** [comment]
@ndt93 Glad to do it, do you have a mapping of log levels from Elixir's Logger to Sentry's? Looking at the code, we're passing:

``` elixir
level: Keyword.get(options, :level, Application.get_env(:ravenex, :logger_level, "error"))
```

So it looks like we're really using what you set for `ravenex`'s log level with a default to "error". Can you just change this in your `config.exs`, e.g.:

**your_app/config/config.exs**:

``` elixir
config :ravenex,
  dsn: { :system, "RAVEN_DSN" },
  logger_level: :warning
```

Let me know if this helps.

**Comment by ndt93** [comment]
@hayesgm Thanks for getting back.

Setting `logger_level` to `warning` doesn't work because the function `meet_level?` in `logger_backend.ex` also uses that value as a parameter for `Logger.compare_levels` which only expects Elixir Logger supported levels.

Elixir Logger supported logger levels as documented [here](http://elixir-lang.org/docs/stable/logger/Logger.html) are:

```
debug
info
warn
error
```

The values expected by Sentry in the `level` attribute as documented [here](https://docs.getsentry.com/hosted/clientdev/attributes/) are

```
fatal
error
warning
info
debug
```

So I think there is only problems with the `warn` level.

**Comment by hayesgm** [comment]
@ndt93 Sure, looking into this, I'm not sure why we have `logger_level` required to be the same as "level to send error as to Sentry." As such, why don't we leave `logger_level` be the threshold for log parsing, and we can create a config option, `level` which is the level of severity to send errors to Sentry. As it stands, we check log level in `handle_event/2`, but we don't pass that to `Ravenex.Notifier.notify/1`.

Proposed solution:

Add new config option `level` which is the level to send to Sentry. Leave `logger_level` as is and only use it for log parsing.

This is a bit of a breaking change because `level` is going to default to "error" (when it used to be the same as `logger_level`).

Thoughts?

**Comment by ndt93** [comment]
Will there be a problem if we want to have different logging levels displayed in Sentry? (since they have different colors and they can be filtered according to their tags etc.).

From what I understand, having the `level` config is going to send all logs to Sentry under that same level.

**Comment by ndt93** [comment]
It's all rights if you think the log levels mapping isn't a fitting behavior here since I can fork the code and implement that behavior for my use case.

Typically users only concern with sending errors to Sentry but I'm integrating with an existing python code base that sends different log levels to a Sentry server; and we are required to investigate both errors and warnings. So I'm trying to keep the Elixir code behavior consistent with the python code.

**Comment by hayesgm** [comment]
Cool, take a look at #2.
